version: '3.8'

services:
  backend:
    build: 
      dockerfile: ./compose/backend/Dockerfile
      context: .
    command: bash -c "alembic upgrade head && uvicorn --port 8000 --host 0.0.0.0 app.main:app"
    env_file:
      - .env
    ports:
      - 127.0.0.1:8000:8000
    volumes:
      - ./data:/data
    depends_on:
      - db

  db:
    image: postgres:14
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  frontend:
    build: 
      dockerfile: ./compose/frontend/Dockerfile
      context: .
    image: frontend
    restart: unless-stopped

  nginx:
    build: 
      dockerfile: ./compose/nginx/Dockerfile
      context: .
    image: nginx
    restart: unless-stopped
    depends_on:
      - backend
      - frontend
    ports:
      - 127.0.0.1:${HTTP_PORT}:80
    volumes:
      - ./mounts/uwsgi:/uwsgi
      - ./mounts/logs/nginx:/var/log/nginx
      - ./mounts/media:/webapp/media:ro
      - ./mounts/static:/webapp/static:ro
