"""init

Revision ID: 058079dbdb47
Revises: 
Create Date: 2022-10-08 12:55:39.823265

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '058079dbdb47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interestingtrend',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interestingtrend_id'), 'interestingtrend', ['id'], unique=True)
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=True)
    op.create_table('trend',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_id'), 'trend', ['id'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('relevant_trends_count', sa.Integer(), nullable=True),
    sa.CheckConstraint('relevant_trends_count <= 10', name='max_relevant_trends_count'),
    sa.CheckConstraint('relevant_trends_count > 0', name='min_relevant_trends_count'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=True)
    op.create_table('role_interesting_trend',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('interesting_trend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interesting_trend_id'], ['interestingtrend.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'interesting_trend_id')
    )
    op.create_table('trendlink',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('link', sa.String(), nullable=True),
    sa.Column('header', sa.String(), nullable=True),
    sa.Column('site_name', sa.String(), nullable=True),
    sa.Column('image_link', sa.String(), nullable=True),
    sa.Column('trend_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trend_id'], ['trend.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trendlink_id'), 'trendlink', ['id'], unique=True)
    op.create_table('user_interesting_trend',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interesting_trend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interesting_trend_id'], ['interestingtrend.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'interesting_trend_id')
    )
    op.create_table('user_trend',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trend_id'], ['trend.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'trend_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_trend')
    op.drop_table('user_interesting_trend')
    op.drop_index(op.f('ix_trendlink_id'), table_name='trendlink')
    op.drop_table('trendlink')
    op.drop_table('role_interesting_trend')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_trend_id'), table_name='trend')
    op.drop_table('trend')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_interestingtrend_id'), table_name='interestingtrend')
    op.drop_table('interestingtrend')
    # ### end Alembic commands ###
