"""change_link

Revision ID: 5963ae9c353b
Revises: 6c4f806406b6
Create Date: 2022-10-08 15:59:13.902896

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '5963ae9c353b'
down_revision = '6c4f806406b6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
