"""Digest image tags

Revision ID: bf1377e2984b
Revises: 1c41b5697816
Create Date: 2022-10-09 07:06:12.507940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf1377e2984b'
down_revision = '1c41b5697816'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('digest', sa.Column('image_tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('digest', 'image_tags')
    # ### end Alembic commands ###