"""init2

Revision ID: d5af732e5415
Revises: 
Create Date: 2022-10-08 22:09:01.625044

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'd5af732e5415'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interestingtheme',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interestingtheme_id'), 'interestingtheme', ['id'], unique=True)
    op.create_table('news',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('url_preview', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_id'), 'news', ['id'], unique=True)
    op.create_table('role',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('code', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_role_id'), 'role', ['id'], unique=True)
    op.create_table('trend',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('topic', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_trend_id'), 'trend', ['id'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('keywords', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('relevant_digests_count', sa.Integer(), nullable=False),
    sa.CheckConstraint('relevant_digests_count <= 10', name='max_relevant_digests_count'),
    sa.CheckConstraint('relevant_digests_count > 0', name='min_relevant_digests_count'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=True)
    op.create_table('digest',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('topic', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_digest_id'), 'digest', ['id'], unique=True)
    op.create_table('role_interesting_theme',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('interesting_theme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interesting_theme_id'], ['interestingtheme.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'interesting_theme_id')
    )
    op.create_table('trend_news',
    sa.Column('trend_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['trend_id'], ['trend.id'], ),
    sa.PrimaryKeyConstraint('trend_id', 'news_id')
    )
    op.create_table('user_interesting_trend',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('interesting_theme_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['interesting_theme_id'], ['interestingtheme.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'interesting_theme_id')
    )
    op.create_table('user_trend',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('trend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['trend_id'], ['trend.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'trend_id')
    )
    op.create_table('digest_news',
    sa.Column('digest_id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['digest_id'], ['digest.id'], ),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.PrimaryKeyConstraint('digest_id', 'news_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('digest_news')
    op.drop_table('user_trend')
    op.drop_table('user_interesting_trend')
    op.drop_table('trend_news')
    op.drop_table('role_interesting_theme')
    op.drop_index(op.f('ix_digest_id'), table_name='digest')
    op.drop_table('digest')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_trend_id'), table_name='trend')
    op.drop_table('trend')
    op.drop_index(op.f('ix_role_id'), table_name='role')
    op.drop_table('role')
    op.drop_index(op.f('ix_news_id'), table_name='news')
    op.drop_table('news')
    op.drop_index(op.f('ix_interestingtheme_id'), table_name='interestingtheme')
    op.drop_table('interestingtheme')
    # ### end Alembic commands ###
